redmine_clear_development: 
  adapter: mysql2
  database: redmine_clear_development
  host: localhost
  username: redmine_clear
  password: ""
  encoding: utf8

redmine_2_5_stable: 
  adapter: mysql2
  database: redmine_2_5_stable
  host: localhost
  username: redmine_clear
  password: ""
  encoding: utf8

test:
  adapter: mysql2
  database: redmine_test
  host: localhost
  username: redmine_test
  password: ""
  encoding: utf8