production:
  adapter:  mysql2
  database: redmine_metrics
  host:     localhost
  username: root
  password: "12345678"
  encoding: utf8

development:
  adapter: mysql2
  database: redmine_clear_development
  host: localhost
  username: redmine_clear
  password: ""
  encoding: utf8